### ISSUE TITLE
DefinePlugin?

### ISSUE THREAD

**Issue by kraftwer1** [timmfin/broccoli-webpack-cached#1]
I'm trying to inject some global variables into my bundle using Webpacks `DefinePlugin`. Unfortunately, I can't get it to work. Does `broccoli-webpack-cached` suppresses this kind of manipulation somehow? Or am I using it the wrong way?

``` javascript
appJs = webpack(appJs, {
    entry: "./app/app.js",
    output: {
        filename: "app.js",
    },
    plugins: [
        new webpackLib.DefinePlugin({
            foo: "bar"
        })
    ],
    devtool: "cheap-module-inline-source-map"
});
```

In browser:

``` javascript
Uncaught ReferenceError: foo is not defined(…)
```

**Comment by timmfin** [comment]
I hadn't used `DefinePlugin` before, and at first I was having the same problem as you. And then after reading around more, I saw how [everyone](https://webpack.github.io/docs/list-of-plugins.html#defineplugin) [was](http://stackoverflow.com/a/30061249/27488) wrapping string literals with `JSON.stringify(...)`. So I gave that a shot and things worked.

In other words, this worked for me:

``` js
    new webpack.DefinePlugin({
      SOME_CUSTOM_VAR: JSON.stringify("Yup, some custom var was inserted here!")
    }),
```

But this didn't:

``` js
    new webpack.DefinePlugin({
      SOME_CUSTOM_VAR: "Yup, some custom var was inserted here!"
    }),
```

Closing, but let me know if you still have any issues.
