### ISSUE TITLE
Webpack throws errors only when using plugin

### ISSUE THREAD

**Issue by rickharrison** [timmfin/broccoli-webpack-cached#8]
When I run `webpack` on the command line, it builds successfully with my config. However, when I try to integrate it into broccoli, this is the error I am getting:

```
Error: Webpack build failures (4):
Module parse failed: /project/node_modules/superagent/package.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "name": "superagent",
|   "version": "0.21.0",
|   "description": "elegant & feature rich browser / node HTTP with a fluent API",

Module not found: Error: Cannot resolve module 'fs' in /project/node_modules/superagent/lib/node
resolve module fs in /project/node_modules/superagent/lib/node
```

Do you have any suggestions on how to resolve this?

**Comment by timmfin** [comment]
This still happening to you?

**Comment by rickharrison** [comment]
So I think this was actually an issue with superagent, but instead of including `superagent` in webpack I ended up doing `superagent/lib/client` and I believe that fixed it.
