### ISSUE TITLE
How to prevent rebuild on changes outside the tree

### ISSUE THREAD

**Issue by rickharrison** [timmfin/broccoli-webpack-cached#9]
I recently switched from browserify to webpack and am now using your great plugin `broccoli-webpack-cached`. Thanks for creating this :)

I am having one issue and that is webpack is rebuilding on _all_ changes, even ones outside its domain. I am currently only using webpack to bundle js, not css, and with my previous `Brocfile`, browserify would not run on a css change. However, now webpack is running on all changes even css files. With browserify, I was able to prevent this behavior like this:

```
let js = new Funnel(js, {
  include: [/.js$/, /.jsx$/],
});

// Now pass the js tree to webpack or browserify
```

Do you have any suggestions on how to prevent rebuilds when changing a file that is not javascript? Thanks!

**Comment by timmfin** [comment]
Hmm, for this plugin I was intentionally deferring to webpack's cache and always kicking off the webpack compiler. So I see how every build is always kicking off Webpack for you.

To fix this, it is in theory as simple as using [broccoli-caching-writer](https://github.com/ember-cli/broccoli-caching-writer) as the base class instead of [broccoli-plugin](https://github.com/broccolijs/broccoli-plugin).  I can try to that...

**Comment by timmfin** [comment]
Ok, so ^ really sent me down a few deep rabbit holes. Moving to `broccoli-caching-writer` helped me discover some webpack caching bugs with filesystems that only have second-level precision, which I reported via https://github.com/webpack/webpack/issues/2003. But as I looked deeper and noticed there was more too it than that, [webpack caching can be pretty broken when using the API directly](https://github.com/webpack/webpack/issues/2003#issuecomment-195403652).

Fortunately, I've tested that [`broccoli-webpack-cached` with `broccoli-caching-writer`](https://github.com/timmfin/broccoli-webpack-cached/compare/use-memory-fs) works well on my [custom fork of webpack](https://github.com/timmfin/webpack/tree/mtime-for-caching), but that probably isn't worth releasing until the core webpack issues are fixed :/ (but I put it out in `broccoli-webpack-cached@0.3.1-beta`)

**Comment by rickharrison** [comment]
Wow, thanks for putting in so much research and work! I really appreciate it.

**Comment by timmfin** [comment]
Closing this (just added a "not maintaining this anymore" message to the readme, so may as well close old issues as well).

**Comment by rickharrison** [comment]
Would you mind adding me as a maintainer so I can fix anything if needed? And adding me on npm as well

**Comment by timmfin** [comment]
Of course, both should be setup now. Thanks a bunch for offering to help continue things!
